apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  namespace: cne
  labels:
    app : flask-app
spec:
  selector:
    app: flask-backend-service
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP