apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sonnyrlm/frontend
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          value: mysql+pymysql://admin:password@cne-project-db-prod.cisxnnla1kct.eu-west-2.rds.amazonaws.com:3306/cne-project-db-prod
        - name: SECRET_KEY
          value: dasfrgasfgvsadgsfvsdhdshnbrgtsb