apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service
  namespace: cne
  labels:
    app: flask-app
spec:
  selector:
    app: flask-frontend-service
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
