apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project-cluster
  region: eu-west-2

vpc:
  id: "vpc-02365063977adeb13"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      eu-west-2a:
        id: "subnet-0b625e7bef0883957"
        cidr: "10.0.1.0/24"
      
      eu-west-2b:
        id: "subnet-0fd6b18f00c4f8ab8"
        cidr: "10.0.2.0/24"

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3