- hosts: all
  become: true
  tasks:
    - name: Clone git repo
      git:
        repo: https://github.com/SonnyRLM/CNE-Project-2
        dest: /home/ubuntu/CNE-Project-2
        version: Dev


    - name: Install misc
      script: /home/ubuntu/CNE-Project-2/scripts/install-misc.sh
    
    - name: Install docker & docker-compose
      script: /home/ubuntu/CNE-Project-2/scripts/install-docker.sh


- hosts: jenkins-vm
  become: true
  tasks:
    - name: Install Jenkins
      script: /home/ubuntu/CNE-Project-2/scripts/install-jenkins.sh
    
    - name: Install k8s
      script: /home/ubuntu/CNE-Project-2/scripts/install-k8.sh

    - name: Install eks
<<<<<<< HEAD
      script: /home/ubuntu/CNE-Project-2/scripts/install-eksctl.sh

    - name: Install AWSCLI
      script: /home/ubuntu/CNE-Project-2/scripts/install-aws.sh

    
=======
      script: /home/ubuntu/CNE-Project/scripts/install-eksctl.sh
>>>>>>> 57ab7afa29003f5d22f15b0a9a2656bfa1038656
