- hosts: all
  become: true
  tasks:
    - name: Install misc
      script: /home/ubuntu/CNE-Project-2/scripts/install-misc.sh
    
    - name: Install docker & docker-compose
      script: /home/ubuntu/CNE-Project-2/scripts/install-docker.sh


- hosts: jenkins-vm
  become: true
  tasks:
    - name: Install Jenkins
      script: /home/ubuntu/CNE-Project-2/scripts/install-jenkins.sh
    
    - name: Install k8s
      script: /home/ubuntu/CNE-Project-2/scripts/install-k8.sh

    - name: Install eks
      script: /home/ubuntu/CNE-Project-2/scripts/install-k8.sh

    - name: Install AWSCLI
      script: /home/ubuntu/CNE-Project-2/scripts/install-aws.sh

    
